// Code generated by packages/contracts/scripts/generate-terraform-policy-contract-go.mjs
// from the canonical policy schema and Terraform disposition manifest. DO NOT EDIT.

package provider

var canonicalContentActions = []string{"allow", "block", "flag_for_review", "redact", "filter", "nudge", "require_approval"}

var canonicalAccessActions = []string{"allow", "block", "flag_for_review", "require_approval"}

var canonicalAccessEnforcementSurfaces = []string{"inline_hook", "endpoint_route", "provider"}

var canonicalAccessSeverities = []string{"low", "medium", "high", "critical"}

var canonicalAccessApprovalModes = []string{"admin_approval", "self_serve"}

var canonicalContentEvaluationPoints = []string{"prompt", "pre_tool", "post_tool", "response"}

var canonicalConditionOperators = []string{"eq", "neq", "in", "not_in", "contains", "contains_any", "contains_all", "starts_with", "ends_with", "matches", "gt", "gte", "lt", "lte", "exists"}

var canonicalCountOperators = []string{"eq", "gt", "gte", "lt", "lte"}

var canonicalContentFields = []string{"identity.user_id", "identity.group_ids", "identity.service_account_id", "request.prompt", "event.kind", "event.title", "event.summary", "event.labels", "event.severity", "tool.server_id", "tool.id", "tool.input", "tool.input.command", "tool.input.file_path", "tool.input.url", "tool.input.workdir", "tool.input.approval", "tool.input.env", "tool.input.surface_kind", "tool.input.surface_key", "tool.result", "response.content", "classification.sensitivity_labels", "classification.data_labels", "classification.categories", "classification.data_source_kinds", "classification.proof_strength", "classification.provider_actions", "classification.has_unresolved_sensitive_content", "mcp.server_id", "mcp.tool_id", "mcp.gateway_endpoint_id", "mcp.package_id", "mcp.package_version", "mcp.remote_url", "llm.model", "llm.provider", "llm.input_tokens", "llm.output_tokens"}

var canonicalAccessFields = []string{"identity.user_id", "identity.group_ids", "device.id", "device.platform", "product.id", "provider.id", "destination.domain", "destination.ip", "destination.port", "process.id", "process.entrypoint_id", "process.name", "process.path", "process.local_port", "browser.extension_id", "browser.extension_identity_id", "browser.extension_surface", "browser.account_id", "browser.account_domain", "browser.account_state", "browser.account_truth_state", "classification.state", "route.posture", "account.posture", "account.access_state", "account.profile_id", "control.path_kind", "source.family", "source.capability", "source.health_state", "local_model.governance_state", "local_model.proof_level", "local_model.name"}

var canonicalConditionKinds = []string{"predicate", "all", "any", "not", "has_prior_event", "has_event_sequence", "event_count", "prior_distinct_values"}

var canonicalRedactionStrategies = []string{"constant", "partial", "hash", "nullify", "fake"}

var canonicalFakeSubtypes = []string{"string", "email", "phone", "ipv4", "payment_card"}

var canonicalFilterOperators = []string{"eq", "neq", "contains", "starts_with", "ends_with", "gt", "gte", "lt", "lte"}

var canonicalFilterUnavailableActions = []string{"allow", "block"}

var canonicalAccessRemediationActions = []string{"clearAuthCookies", "clearCacheStorage", "clearCookies", "clearExtensionStateWhenProven", "clearIndexedDb", "clearServiceWorkers", "clearSiteStorage", "clearStorage", "closeTabOrWindow", "disableLaunchService", "disableLoginItem", "disableManagedExtension", "disableManagedPlugin", "disableManagedServerConfig", "disableManagedToolConfig", "forceTerminate", "gracefulQuit", "killHelperProcess", "managedUninstall", "preventReinstall", "quarantine", "quarantineBinary", "quarantineRuntime", "removeManagedConfigEntry", "removeManagedConfiguration", "removeManagedExtension", "removeManagedPlugin", "removePackageWhenOwned", "removePluginConfigWhenProven", "removeSitePermissions", "revokeTokenWhenProven", "rotateSecretWhenProven", "stopCallerProcessWhenProven", "stopContainerWhenKnown", "stopLocalServerProcess", "stopServer", "terminateRuntime"}

var canonicalSkillEffects = []string{"allow", "block"}

var canonicalPolicyUseCases = []string{"Data Encryption", "Public Exposure", "Data Sprawl", "Organizational Access", "Resilience", "Runtime Safety", "Credential Risk", "AI Model Governance", "Shadow AI"}

var canonicalComplianceFrameworks = []string{"Security Basics", "NIST", "CIS", "GDPR", "HIPAA", "PCI DSS", "SOC 2", "OWASP"}

var canonicalContentFieldTypes = map[string]string{"classification.categories": "string_set",
	"classification.data_labels":                      "string_set",
	"classification.data_source_kinds":                "string_set",
	"classification.has_unresolved_sensitive_content": "boolean",
	"classification.proof_strength":                   "string",
	"classification.provider_actions":                 "string_set",
	"classification.sensitivity_labels":               "string_set",
	"event.kind":                                      "string",
	"event.labels":                                    "string_set",
	"event.severity":                                  "string",
	"event.summary":                                   "string",
	"event.title":                                     "string",
	"identity.group_ids":                              "string_set",
	"identity.service_account_id":                     "string",
	"identity.user_id":                                "string",
	"llm.input_tokens":                                "number",
	"llm.model":                                       "string",
	"llm.output_tokens":                               "number",
	"llm.provider":                                    "string",
	"mcp.gateway_endpoint_id":                         "string",
	"mcp.package_id":                                  "string",
	"mcp.package_version":                             "string",
	"mcp.remote_url":                                  "string",
	"mcp.server_id":                                   "string",
	"mcp.tool_id":                                     "string",
	"request.prompt":                                  "string",
	"response.content":                                "string",
	"tool.id":                                         "string",
	"tool.input":                                      "content",
	"tool.input.approval":                             "string",
	"tool.input.command":                              "string",
	"tool.input.env":                                  "content",
	"tool.input.file_path":                            "string",
	"tool.input.surface_key":                          "string",
	"tool.input.surface_kind":                         "string",
	"tool.input.url":                                  "string",
	"tool.input.workdir":                              "string",
	"tool.result":                                     "content",
	"tool.server_id":                                  "string"}
var canonicalAccessFieldTypes = map[string]string{"account.access_state": "string",
	"account.posture":               "string",
	"account.profile_id":            "string_set",
	"browser.account_domain":        "string",
	"browser.account_id":            "string",
	"browser.account_state":         "string",
	"browser.account_truth_state":   "string",
	"browser.extension_id":          "string",
	"browser.extension_identity_id": "string",
	"browser.extension_surface":     "string",
	"classification.state":          "string",
	"control.path_kind":             "string",
	"destination.domain":            "string",
	"destination.ip":                "string",
	"destination.port":              "number",
	"device.id":                     "string",
	"device.platform":               "string",
	"identity.group_ids":            "string_set",
	"identity.user_id":              "string",
	"local_model.governance_state":  "string",
	"local_model.name":              "string_set",
	"local_model.proof_level":       "string",
	"process.entrypoint_id":         "string",
	"process.id":                    "string",
	"process.local_port":            "number",
	"process.name":                  "string",
	"process.path":                  "string",
	"product.id":                    "string",
	"provider.id":                   "string",
	"route.posture":                 "string",
	"source.capability":             "string_set",
	"source.family":                 "string",
	"source.health_state":           "string"}
var canonicalAccessFieldValueOptions = map[string][]string{"account.access_state": {"approved_access", "unapproved_access", "unknown_access", "cannot_prove_access", "conflicting_access"},
	"account.posture":              {"sso_verified", "non_sso_verified", "account_unknown", "cannot_prove_account"},
	"browser.account_state":        {"company_account", "personal_account", "service_account", "account_unknown", "cannot_prove_account"},
	"browser.account_truth_state":  {"metadata_observed", "unknown", "stale", "hinted", "inferred", "proven"},
	"classification.state":         {"known_ai", "candidate_ai", "known_not_ai", "uncertain", "no_catalog_match"},
	"local_model.governance_state": {"approved", "unknown", "disallowed"},
	"local_model.proof_level":      {"request-declared", "running", "available", "unknown"},
	"route.posture":                {"unmanaged_route", "unknown_route", "uncontrolled", "managed_route", "delegated_control_route", "approved_route", "forbidden_route"},
	"source.health_state":          {"active", "degraded", "stale", "missing", "disabled", "unhealthy"}}
var canonicalOperatorsByFieldType = map[string][]string{"boolean": {"eq", "neq", "exists"},
	"content":    {"eq", "neq", "contains", "starts_with", "ends_with", "matches", "exists"},
	"number":     {"eq", "neq", "in", "not_in", "gt", "gte", "lt", "lte", "exists"},
	"object":     {"exists"},
	"string":     {"eq", "neq", "in", "not_in", "contains", "starts_with", "ends_with", "matches", "exists"},
	"string_set": {"eq", "neq", "contains", "contains_any", "contains_all", "exists"}}

const canonicalConditionDurationPattern = "^[1-9][0-9]*(s|m|h|d)$"
const canonicalConditionMaxChildren = 64
const canonicalSequenceMaxEvents = 16
const canonicalConditionCountMaximum = 1024
